// File Upload Component
// Generated by [N]skills

'use client';

import { useState, useCallback } from 'react';
import { useIPFS } from '@/hooks/useIPFS';

interface FileUploadProps {
  onUpload?: (result: { cid: string; url: string }) => void;
  accept?: string;
  className?: string;
}

export function FileUpload({ onUpload, accept, className }: FileUploadProps) {
  const { upload, isUploading, error, lastUpload } = useIPFS();
  const [dragActive, setDragActive] = useState(false);
  
  const handleFile = useCallback(async (file: File) => {
    try {
      const result = await upload(file);
      onUpload?.(result);
    } catch {
      // Error handled by hook
    }
  }, [upload, onUpload]);
  
  const handleDrop = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    setDragActive(false);
    
    const file = e.dataTransfer.files[0];
    if (file) handleFile(file);
  }, [handleFile]);
  
  const handleChange = useCallback((e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) handleFile(file);
  }, [handleFile]);
  
  return (
    <div className={className}>
      <div
        onDragOver={(e) => { e.preventDefault(); setDragActive(true); }}
        onDragLeave={() => setDragActive(false)}
        onDrop={handleDrop}
        className={`border-2 border-dashed rounded-lg p-8 text-center transition-colors ${
          dragActive ? 'border-emerald-500 bg-emerald-500/10' : 'border-zinc-700'
        }`}
      >
        <input
          type="file"
          accept={accept}
          onChange={handleChange}
          className="hidden"
          id="file-upload"
          disabled={isUploading}
        />
        <label htmlFor="file-upload" className="cursor-pointer">
          {isUploading ? (
            <p className="text-zinc-400">Uploading...</p>
          ) : (
            <>
              <p className="text-white mb-2">Drop file here or click to upload</p>
              <p className="text-xs text-zinc-500">Files are stored on IPFS</p>
            </>
          )}
        </label>
      </div>
      
      {error && (
        <p className="mt-2 text-sm text-red-400">{error.message}</p>
      )}
      
      {lastUpload && (
        <div className="mt-3 p-3 bg-zinc-800 rounded-md">
          <p className="text-xs text-zinc-400 mb-1">Uploaded to IPFS</p>
          <a href={lastUpload.url} target="_blank" rel="noopener noreferrer"
             className="text-sm text-emerald-400 hover:underline break-all">
            {lastUpload.url}
          </a>
        </div>
      )}
    </div>
  );
}

export default FileUpload;