// IPFS Storage Hooks
// Generated by [N]skills

'use client';

import { useState, useCallback } from 'react';
import { uploadFile, uploadJSON, getIPFSUrl, type UploadResult } from '@/lib/storage/storage-client';

export interface UseIPFSReturn {
  upload: (file: File) => Promise<UploadResult>;
  uploadMetadata: (metadata: object, name?: string) => Promise<UploadResult>;
  isUploading: boolean;
  error: Error | null;
  lastUpload: UploadResult | null;
}

export function useIPFS(): UseIPFSReturn {
  const [isUploading, setIsUploading] = useState(false);
  const [error, setError] = useState<Error | null>(null);
  const [lastUpload, setLastUpload] = useState<UploadResult | null>(null);
  
  const upload = useCallback(async (file: File) => {
    setIsUploading(true);
    setError(null);
    
    try {
      const result = await uploadFile(file);
      setLastUpload(result);
      return result;
    } catch (err) {
      const e = err instanceof Error ? err : new Error('Upload failed');
      setError(e);
      throw e;
    } finally {
      setIsUploading(false);
    }
  }, []);
  
  const uploadMetadata = useCallback(async (metadata: object, name?: string) => {
    setIsUploading(true);
    setError(null);
    
    try {
      const result = await uploadJSON(metadata, name);
      setLastUpload(result);
      return result;
    } catch (err) {
      const e = err instanceof Error ? err : new Error('Upload failed');
      setError(e);
      throw e;
    } finally {
      setIsUploading(false);
    }
  }, []);
  
  return { upload, uploadMetadata, isUploading, error, lastUpload };
}

export { getIPFSUrl };