// Pinata IPFS Client
// Generated by [N]skills

const PINATA_API_KEY = process.env.PINATA_API_KEY;
const PINATA_SECRET_KEY = process.env.PINATA_SECRET_KEY;
const PINATA_GATEWAY = process.env.NEXT_PUBLIC_PINATA_GATEWAY ?? 'https://gateway.pinata.cloud';

export interface UploadResult {
  cid: string;
  url: string;
  size: number;
}

export async function uploadFile(file: File): Promise<UploadResult> {
  const formData = new FormData();
  formData.append('file', file);
  
  const response = await fetch('https://api.pinata.cloud/pinning/pinFileToIPFS', {
    method: 'POST',
    headers: { 
      pinata_api_key: PINATA_API_KEY,
      pinata_secret_api_key: PINATA_SECRET_KEY
    },
    body: formData,
  });
  
  if (!response.ok) throw new Error('Upload failed');
  
  const data = await response.json();
  return {
    cid: data.IpfsHash,
    url: `${PINATA_GATEWAY}/ipfs/${data.IpfsHash}`,
    size: data.PinSize,
  };
}

export async function uploadJSON(json: object, name?: string): Promise<UploadResult> {
  const response = await fetch('https://api.pinata.cloud/pinning/pinJSONToIPFS', {
    method: 'POST',
    headers: {
      pinata_api_key: PINATA_API_KEY,
      pinata_secret_api_key: PINATA_SECRET_KEY,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      pinataContent: json,
      pinataMetadata: { name: name ?? 'metadata.json' },
    }),
  });
  
  if (!response.ok) throw new Error('Upload failed');
  
  const data = await response.json();
  return {
    cid: data.IpfsHash,
    url: `${PINATA_GATEWAY}/ipfs/${data.IpfsHash}`,
    size: data.PinSize,
  };
}

export function getIPFSUrl(cid: string): string {
  return `${PINATA_GATEWAY}/ipfs/${cid}`;
}